# Generated by Django 5.1.6 on 2025-04-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['sort', 'name'], 'verbose_name': 'car', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort', 'name'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterModelTable(
            name='car',
            table='main_cars',
        ),
        migrations.AlterModelTable(
            name='category',
            table='main_categories',
        ),
    ]
